[workspace]
authors = ["Hong-yiii <hongyilin.mail@gmail.com>"]
channels = ["conda-forge"]
name = "framed_3b"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
jsonschema = ">=4.25.1,<5"
pillow = ">=10.0.0,<11"
piexif = ">=1.1.3,<2"
numpy = ">=2.3.3,<3"
pillow-heif = ">=0.20.0,<1"
# ML dependencies
pytorch = ">=2.1.0,<3"
torchvision = ">=0.16.0,<1"
# Image processing and quality assessment
opencv = ">=4.8.0,<5"
scikit-image = ">=0.22.0,<1"
# Image Quality Assessment
piq = ">=0.8.0,<1"

[pypi-dependencies]
open-clip-torch = ">=2.26.1,<3"
